wandb_name: "lr0.001_d0.05"
wandb_project: "hyperparamter_tuning"
train_data: "train_dataset_NE_480.nc"
val_data: "validation_dataset_NE_480.nc"
seed: 0
batch_size: 4
epochs: 20
input_shape: [4, 480, 480, 1]
learning_rate: 0.001
dropout: 0.05